services:
  eventstore.db:
    image: ghcr.io/eventstore/eventstore:21.10.5-alpha-arm64v8
    environment:
      - EVENTSTORE_CLUSTER_SIZE=1
      - EVENTSTORE_RUN_PROJECTIONS=All
      - EVENTSTORE_START_STANDARD_PROJECTIONS=true
      - EVENTSTORE_INSECURE=true
      - EVENTSTORE_ENABLE_EXTERNAL_TCP=true
      - EVENTSTORE_ENABLE_ATOM_PUB_OVER_HTTP=true
    ports:
      - 1113:1113
      - 2113:2113
    volumes:
      - type: volume
        source: eventstore-volume-data
        target: /var/lib/eventstore
      - type: volume
        source: eventstore-volume-logs
        target: /var/log/eventstore

  mongo.db:
    image: mongo
    container_name: ticksbook-api.mongo-db
    environment:
      - MONGO_INITDB_ROOT_USERNAME=root
      - MONGO_INITDB_ROOT_PASSWORD=root
    ports:
      - 27017:27017
    volumes:
      - type: volume
        source: mongo-volume-data
        target: /var/lib/mongo

  mongo-express:
    image: mongo-express
    depends_on:
      - mongo.db
    environment:
      - ME_CONFIG_MONGODB_SERVER=ticksbook-api.mongo-db
      - ME_CONFIG_MONGODB_ADMINUSERNAME=root
      - ME_CONFIG_MONGODB_ADMINPASSWORD=root
    ports:
      - 8081:8081
    restart: unless-stopped

volumes:
  eventstore-volume-data:
  eventstore-volume-logs:
  mongo-volume-data:
